/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package epic.dfcc.ceft.iso_depacker;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Properties;

/**
 *
 * @author lashan_chandika
 */
class ConfigXM {

    private static final String DEF_XML_FILE_PATH = "C:/ISO_Unpacker_Config/cbsiso87binary.xml";

    public static String initXML() {
        String xml_path = DEF_XML_FILE_PATH;
        try {
            String baseDir = System.getProperty("os.name").toLowerCase().contains("win")
                    ? "C:/ISO_Unpacker_Config"
                    : "/opt/ISO_Unpacker_Config";

            String configFilePath = baseDir + "/config.properties";
            Files.createDirectories(Paths.get(baseDir));

            Properties properties = new Properties();
            File configFile = new File(configFilePath);

            if (configFile.exists()) {
                try (FileInputStream fis = new FileInputStream(configFile)) {
                    properties.load(fis);
                }
            }

            String isoXmPath = properties.getProperty("iso.xm.path");
            if (isoXmPath != null && !isoXmPath.trim().equals("")) {
                return isoXmPath;
            }

            System.out.println("Current iso.xm.path: " + isoXmPath);
            if (isoXmPath == null || isoXmPath.trim().equals("")) {
                System.out.println("New iso.xm.path: " + isoXmPath);
                properties.setProperty("iso.xm.path", DEF_XML_FILE_PATH);

                try (FileOutputStream fos = new FileOutputStream(configFile)) {
                    properties.store(fos, "ISO Unpacker Configuration");
                }
                xml_path = DEF_XML_FILE_PATH;
                System.out.println("Updated iso.xm.path saved to: " + configFilePath);
            }

        } catch (IOException e) {
            e.printStackTrace();
        }

        return xml_path;
    }

    static void reWrite(String path) {
        try {
            String baseDir = System.getProperty("os.name").toLowerCase().contains("win")
                    ? "C:/ISO_Unpacker_Config"
                    : "/opt/ISO_Unpacker_Config";

            String configFilePath = baseDir + "/config.properties";
            Files.createDirectories(Paths.get(baseDir));

            Properties properties = new Properties();
            File configFile = new File(configFilePath);

            if (configFile.exists()) {
                try (FileInputStream fis = new FileInputStream(configFile)) {
                    properties.load(fis);
                }
            }
            properties.setProperty("iso.xm.path", DEF_XML_FILE_PATH);
            try (FileOutputStream fos = new FileOutputStream(configFile)) {
                properties.store(fos, "ISO Unpacker Configuration");
            }

            System.out.println("Updated iso.xm.path saved to: " + configFilePath);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void xmlIsExsist(String xml_path) {
        try {
            String xmlContent = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
                    + "<!DOCTYPE isopackager SYSTEM \"genericpackager.dtd\">\n"
                    + "\n"
                    + "<!-- ISO 8583:1993 (BINARY) field descriptions for GenericPackager -->\n"
                    + "\n"
                    + "<isopackager>\n"
                    + "  <isofield\n"
                    + "      id=\"0\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Message Type Indicator\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "          id=\"1\"\n"
                    + "      length=\"16\"\n"
                    + "      name=\"BIT MAP\"\n"
                    + "      class=\"org.jpos.iso.IFB_BITMAP\"/>\n"
                    + " <isofield\n"
                    + "      id=\"2\"\n"
                    + "      length=\"19\"\n"
                    + "      name=\"Primary Account number\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLNUM\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"3\"\n"
                    + "      length=\"6\"\n"
                    + "      name=\"Processing Code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"4\"\n"
                    + "      length=\"12\"\n"
                    + "      name=\"Amount, Transaction\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_AMOUNT\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"5\"\n"
                    + "      length=\"12\"\n"
                    + "      name=\"Amount, Reconciliation\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_AMOUNT\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"6\"\n"
                    + "      length=\"16\"\n"
                    + "      name=\"Amount, Cardholder billing\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_AMOUNT\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"7\"\n"
                    + "      length=\"10\"\n"
                    + "      name=\"Date and time, transmission\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"8\"\n"
                    + "      length=\"12\"\n"
                    + "      name=\"Amount, Cardholder billing fee\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_AMOUNT\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"9\"\n"
                    + "      length=\"8\"\n"
                    + "      name=\"Conversion rate, Reconciliation\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"10\"\n"
                    + "      length=\"8\"\n"
                    + "      name=\"Conversion rate, Cardholder billing\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"11\"\n"
                    + "      length=\"6\"\n"
                    + "      name=\"Systems trace audit number\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"12\"\n"
                    + "      length=\"6\"\n"
                    + "      name=\"Date and time, Local transaction\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"13\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Date, Effective\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"14\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Date, Expiration\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"15\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Date, Settlement\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"16\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Date, Conversion\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"17\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Date, Capture\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"18\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Message error indicator\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"19\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Country code, Acquiring institution\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"20\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Country code, Primary account number\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"21\"\n"
                    + "      length=\"22\"\n"
                    + "      name=\"Transaction life cycle identification data\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IF_CHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"22\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Point of service data code\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"23\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Card sequence number\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"24\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Function code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IF_CHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"25\"\n"
                    + "      length=\"2\"\n"
                    + "      name=\"Message reason code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"26\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Merchant category code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"27\"\n"
                    + "      length=\"27\"\n"
                    + "      name=\"POS capability\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_BINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"28\"\n"
                    + "      length=\"9\"\n"
                    + "      name=\"Date, Reconciliation\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"29\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Reconciliation indicator\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"30\"\n"
                    + "      length=\"32\"\n"
                    + "      name=\"Amounts original\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"31\"\n"
                    + "      length=\"23\"\n"
                    + "      name=\"Acquirer reference number\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"32\"\n"
                    + "      length=\"11\"\n"
                    + "      name=\"Acquirer institution identfication code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLNUM\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"33\"\n"
                    + "      length=\"16\"\n"
                    + "      name=\"Forwarding institution identification code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLNUM\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"34\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Electronic commerce data\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"35\"\n"
                    + "      length=\"37\"\n"
                    + "      name=\"Track 2 data\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLNUM\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"36\"\n"
                    + "      length=\"104\"\n"
                    + "      name=\"Track 3 data\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"37\"\n"
                    + "      length=\"12\"\n"
                    + "      name=\"Retrieval reference number\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"38\"\n"
                    + "      length=\"6\"\n"
                    + "      name=\"Approval code\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"39\"\n"
                    + "      length=\"2\"\n"
                    + "      name=\"Action code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"40\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Service code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"41\"\n"
                    + "      length=\"8\"\n"
                    + "      name=\"Card acceptor terminal identification\"\n"
                    + "      class=\"org.jpos.iso.IF_CHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"42\"\n"
                    + "      length=\"15\"\n"
                    + "      name=\"Card acceptor identification code\"\n"
                    + "      class=\"org.jpos.iso.IF_CHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"43\"\n"
                    + "      length=\"40\"\n"
                    + "      name=\"Card acceptor name/location\"\n"
                    + "      class=\"org.jpos.iso.IF_CHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"44\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Additional response data\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"45\"\n"
                    + "      length=\"76\"\n"
                    + "      name=\"Track 1 data\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"46\"\n"
                    + "      length=\"216\"\n"
                    + "      name=\"Amounts fees\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"47\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Additional data national\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"48\"\n"
                    + "      length=\"512\"\n"
                    + "      name=\"Additional data private\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"49\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Verification data\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"50\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"51\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"52\"\n"
                    + "      length=\"8\"\n"
                    + "      name=\"PIN data\"\n"
                    + "      class=\"org.jpos.iso.IFB_BINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"53\"\n"
                    + "      length=\"48\"\n"
                    + "      name=\"Security related control information\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"54\"\n"
                    + "      length=\"40\"\n"
                    + "      name=\"Amounts, additional\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLLCHAR\"/>  <!--IFB_LLLCHAR convert to IFA_LLLCHAR by dimuthu -->\n"
                    + "  <isofield\n"
                    + "      id=\"55\"\n"
                    + "      length=\"255\"\n"
                    + "      name=\"IC system related data\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLLNUM\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"56\"\n"
                    + "      length=\"43\"\n"
                    + "      name=\"Original data elements\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"57\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"Authorization life cycle code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"58\"\n"
                    + "      length=\"11\"\n"
                    + "      name=\"Authorizing agent institution identification code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLNUM\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"59\"\n"
                    + "      length=\"99\"\n"
                    + "      name=\"Transport data\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"60\"\n"
                    + "      length=\"6\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"61\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"62\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"63\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"64\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Message authentication code field\"\n"
                    + "      class=\"org.jpos.iso.IFB_BINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"65\"\n"
                    + "      length=\"8\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      class=\"org.jpos.iso.IFB_BINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"66\"\n"
                    + "      length=\"216\"\n"
                    + "      name=\"Amounts, original fees\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"67\"\n"
                    + "      length=\"2\"\n"
                    + "      name=\"Extended payment data\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"68\"\n"
                    + "      length=\"9\"\n"
                    + "      name=\"Batch/file transfer message control\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IF_CHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"69\"\n"
                    + "      length=\"40\"\n"
                    + "      name=\"Batch/file transfer control data\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IF_CHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"70\"\n"
                    + "      length=\"3\"\n"
                    + "      name=\"File transfer description data\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"71\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"72\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Data record\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"73\"\n"
                    + "      length=\"8\"\n"
                    + "      name=\"Date action\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"74\"\n"
                    + "      length=\"78\"\n"
                    + "      name=\"Reconciliation data primary\"\n"
                    + "      class=\"org.jpos.iso.IFB_BINARY\"\n"
                    + "      />\n"
                    + "  <isofield\n"
                    + "      id=\"75\"\n"
                    + "      length=\"90\"\n"
                    + "      name=\"Reconciliation data secondary\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_NUMERIC\"/>\n"
                    + "  <isofield id=\"76\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"77\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"78\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"79\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"80\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"81\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"82\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"83\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"84\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"85\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"86\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"87\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"88\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"89\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"90\"\n"
                    + "      length=\"43\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_NUMERIC\"/>\n"
                    + "  <isofield id=\"96\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield id=\"92\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"93\"\n"
                    + "      length=\"11\"\n"
                    + "      name=\"Transaction destination institution identification code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"94\"\n"
                    + "      length=\"11\"\n"
                    + "      name=\"Transaction originator institution identification code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"95\"\n"
                    + "      length=\"99\"\n"
                    + "      name=\"Card issuer reference data\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"96\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Key management data\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"97\"\n"
                    + "      length=\"21\"\n"
                    + "      name=\"Amount, Net reconciliation\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_AMOUNT\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"98\"\n"
                    + "      length=\"25\"\n"
                    + "      name=\"Payee\"\n"
                    + "      class=\"org.jpos.iso.IF_CHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"99\"\n"
                    + "      length=\"11\"\n"
                    + "      name=\"Settlement institution identification code\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"100\"\n"
                    + "      length=\"11\"\n"
                    + "      name=\"Receiving institution identification code\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLNUM\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"101\"\n"
                    + "      length=\"99\"\n"
                    + "      name=\"File name\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"102\"\n"
                    + "      length=\"16\"\n"
                    + "      name=\"Account identification 1\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"103\"\n"
                    + "      length=\"12\"\n"
                    + "      name=\"Account identification 2\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"104\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Transaction specific data\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"105\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"106\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"107\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"108\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for ISO use\"\n"
                    + "      pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "\n"
                    + "  <isofield\n"
                    + "      id=\"109\"\n"
                    + "      length=\"144\"\n"
                    + "      name=\"Reconciliation fee amounts credit\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"110\"\n"
                    + "      length=\"144\"\n"
                    + "      name=\"Reconciliation fee amounts debit\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"111\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"112\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"113\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"114\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"115\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"116\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"117\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"118\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"119\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"120\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLLNUM\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"121\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"122\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for national use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"123\"\n"
                    + "      length=\"99\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "       pad=\"false\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"124\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"125\"\n"
                    + "      length=\"999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFA_LLLCHAR\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"126\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"127\"\n"
                    + "      length=\"9999\"\n"
                    + "      name=\"Reserved for private use\"\n"
                    + "      class=\"org.jpos.iso.IFB_LLLLBINARY\"/>\n"
                    + "  <isofield\n"
                    + "      id=\"128\"\n"
                    + "      length=\"4\"\n"
                    + "      name=\"Message authentication code field\"\n"
                    + "      class=\"org.jpos.iso.IFB_BINARY\"/>\n"
                    + "</isopackager>";
            File file = new File(xml_path);
            if (file.exists()) {
                return;
            }

            if (file.createNewFile()) {
                try (FileWriter writer = new FileWriter(file)) {
                    writer.write(xmlContent);
                }

                System.out.println("File created successfully: " + xml_path);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

}
